import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from "@/components/banner/Banner";
import Navbar from "@/components/nav/Navbar";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar username={'Oleg@mail.com'}/>

      <Banner
        title={'Clifford the red dog'}
        subtitle={'a vary cure dog'}
        imgUrl={'/static/clifford.webp'}
      />
    </>
  )
}
